### PR TITLE
Create The FitnessGram Pacer Test is a multistage aerobic capacity te…

### PR DESCRIPTION
**Pull request by SEAPUNK**
…st that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly but gets faster each minute after you hear this signal bodeboop. A sing lap should be completed every time you hear this sound. ding Remember to run in a straight line and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark..html

The FitnessGram Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly but gets faster each minute after you hear this signal bodeboop. A sing lap should be completed every time you hear this sound. ding Remember to run in a straight line and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark.

### CODE REVIEW

**Comment by SEAPUNK** [comment]
fixes #1

**Comment by SEAPUNK** [comment]
fixes #2

**Comment by SEAPUNK** [comment]
@Getindor @Getindor @Getindor

**Comment by SEAPUNK** [comment]
@Getindor

**Comment by Getindor** [comment]
YE

**Comment by SEAPUNK** [comment]
mark mark mark mark

**Comment by Getindor** [comment]
10/10

**Pull request merged**
